// <auto-generated />
using System;
using ArtezaStudio.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtezaStudio.Api.Migrations
{
    [DbContext(typeof(ArtezaContext))]
    [Migration("20250619162956_TagsPublicacao")]
    partial class TagsPublicacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataComentario")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PublicacaoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PublicacaoId1")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UsuarioId1")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.HasIndex("PublicacaoId1");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Curtida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCurtida")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PublicacaoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PublicacaoId1")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.HasIndex("PublicacaoId1");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Curtidas");
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Publicacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Publicacoes");
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.PublicacaoTag", b =>
                {
                    b.Property<Guid>("PublicacaoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("char(36)");

                    b.HasKey("PublicacaoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PublicacaoTags");
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemPerfilUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Visualizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataVisualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PublicacaoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PublicacaoId1")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.HasIndex("PublicacaoId1");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Visualizacoes");
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Comentario", b =>
                {
                    b.HasOne("ArtezaStudio.Api.Entities.Publicacao", "Publicacao")
                        .WithMany()
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtezaStudio.Api.Entities.Publicacao", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacaoId1");

                    b.HasOne("ArtezaStudio.Api.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtezaStudio.Api.Entities.Usuario", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Publicacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Curtida", b =>
                {
                    b.HasOne("ArtezaStudio.Api.Entities.Publicacao", "Publicacao")
                        .WithMany()
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtezaStudio.Api.Entities.Publicacao", null)
                        .WithMany("Curtidas")
                        .HasForeignKey("PublicacaoId1");

                    b.HasOne("ArtezaStudio.Api.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Publicacao", b =>
                {
                    b.HasOne("ArtezaStudio.Api.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.PublicacaoTag", b =>
                {
                    b.HasOne("ArtezaStudio.Api.Entities.Publicacao", "Publicacao")
                        .WithMany("PublicacaoTags")
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtezaStudio.Api.Entities.Tag", "Tag")
                        .WithMany("PublicacaoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Visualizacao", b =>
                {
                    b.HasOne("ArtezaStudio.Api.Entities.Publicacao", "Publicacao")
                        .WithMany()
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtezaStudio.Api.Entities.Publicacao", null)
                        .WithMany("Visualizacoes")
                        .HasForeignKey("PublicacaoId1");

                    b.HasOne("ArtezaStudio.Api.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Publicacao", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Curtidas");

                    b.Navigation("PublicacaoTags");

                    b.Navigation("Visualizacoes");
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Tag", b =>
                {
                    b.Navigation("PublicacaoTags");
                });

            modelBuilder.Entity("ArtezaStudio.Api.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
