// <auto-generated />
using System;
using ArtezaStudio.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtezaStudio.Infrastructure.Migrations
{
    [DbContext(typeof(ArtezaContext))]
    partial class ArtezaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Comentario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataComentario")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PublicacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PublicacaoId1")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.HasIndex("PublicacaoId1");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Curtida", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCurtida")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PublicacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PublicacaoId1")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.HasIndex("PublicacaoId1");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Curtidas");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Publicacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Publicacoes");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.PublicacaoTag", b =>
                {
                    b.Property<long>("PublicacaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.HasKey("PublicacaoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PublicacaoTags");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemPerfilUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.UsuarioSeguidor", b =>
                {
                    b.Property<long>("SeguidorId")
                        .HasColumnType("bigint");

                    b.Property<long>("SeguidoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataSeguimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioId1")
                        .HasColumnType("bigint");

                    b.HasKey("SeguidorId", "SeguidoId");

                    b.HasIndex("SeguidoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("usuarioSeguidores");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Visualizacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataVisualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PublicacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PublicacaoId1")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.HasIndex("PublicacaoId1");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Visualizacoes");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("ArtezaStudio.Domain.Entities.Publicacao", "Publicacao")
                        .WithMany()
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtezaStudio.Domain.Entities.Publicacao", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacaoId1");

                    b.HasOne("ArtezaStudio.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtezaStudio.Domain.Entities.Usuario", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Publicacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Curtida", b =>
                {
                    b.HasOne("ArtezaStudio.Domain.Entities.Publicacao", "Publicacao")
                        .WithMany()
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtezaStudio.Domain.Entities.Publicacao", null)
                        .WithMany("Curtidas")
                        .HasForeignKey("PublicacaoId1");

                    b.HasOne("ArtezaStudio.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Publicacao", b =>
                {
                    b.HasOne("ArtezaStudio.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.PublicacaoTag", b =>
                {
                    b.HasOne("ArtezaStudio.Domain.Entities.Publicacao", "Publicacao")
                        .WithMany("PublicacaoTags")
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtezaStudio.Domain.Entities.Tag", "Tag")
                        .WithMany("PublicacaoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.UsuarioSeguidor", b =>
                {
                    b.HasOne("ArtezaStudio.Domain.Entities.Usuario", "Seguido")
                        .WithMany()
                        .HasForeignKey("SeguidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtezaStudio.Domain.Entities.Usuario", "Seguidor")
                        .WithMany()
                        .HasForeignKey("SeguidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtezaStudio.Domain.Entities.Usuario", null)
                        .WithMany("Seguidores")
                        .HasForeignKey("UsuarioId");

                    b.HasOne("ArtezaStudio.Domain.Entities.Usuario", null)
                        .WithMany("Seguindo")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Seguido");

                    b.Navigation("Seguidor");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Visualizacao", b =>
                {
                    b.HasOne("ArtezaStudio.Domain.Entities.Publicacao", "Publicacao")
                        .WithMany()
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtezaStudio.Domain.Entities.Publicacao", null)
                        .WithMany("Visualizacoes")
                        .HasForeignKey("PublicacaoId1");

                    b.HasOne("ArtezaStudio.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Publicacao", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Curtidas");

                    b.Navigation("PublicacaoTags");

                    b.Navigation("Visualizacoes");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Tag", b =>
                {
                    b.Navigation("PublicacaoTags");
                });

            modelBuilder.Entity("ArtezaStudio.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Seguidores");

                    b.Navigation("Seguindo");
                });
#pragma warning restore 612, 618
        }
    }
}
